name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/kumu-coaching || git clone git@github.com:Usamahafiz8/kumu-coaching.git ~/kumu-coaching
            cd ~/kumu-coaching
            git pull origin main
            npm install
            npm run build
            pm2 restart kumu-coaching || pm2 start dist/main.js --name kumu-coaching
